spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      dbStorage:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
